### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lymanyoung** [yanwii/dynamic-seq2seq#7]
Traceback (most recent call last):
  File "seq2seq.py", line 382, in <module>
    seq = seq2seq()
  File "seq2seq.py", line 54, in __init__
    time_major=True)
  File "/Users/LymanYoung/source/git_tensorflow/seq2seq-demo/dynamic-seq2seq/dynamic_seq2seq_model.py", line 61, in __init__
    self._make_graph()
  File "/Users/LymanYoung/source/git_tensorflow/seq2seq-demo/dynamic-seq2seq/dynamic_seq2seq_model.py", line 85, in _make_graph
    self._init_decoder()
  File "/Users/LymanYoung/source/git_tensorflow/seq2seq-demo/dynamic-seq2seq/dynamic_seq2seq_model.py", line 221, in _init_decoder
    decoder_fn_train = seq2seq.simple_decoder_fn_train(encoder_state=self.encoder_state)
AttributeError: module 'tensorflow.contrib.seq2seq' has no attribute 'simple_decoder_fn_train'

**Comment by yanwii** [comment]
该项目使用的是tensorflow-1.0的版本，请自行调整。

**Comment by fooSynaptic** [comment]
> 该项目使用的是tensorflow-1.0的版本，请自行调整。

更高版本的tensorflow有可以替代的接口吗
